; Generated by scripts/sync-branding.mjs from branding/brand.json. Do not edit directly.
#define BrandAppName "Pudding Box"
#define BrandAppPublisher "Pudding Box Studio"
#define BrandAppPublisherURL "https://puddingbox.example"
