package brand

import (
	_ "embed"
	"encoding/json"
	"strings"
	"sync"
)

// Config is the single source of user-facing product identity. The source of
// truth is branding/brand.json; internal/brand/brand.json is generated by
// scripts/sync-branding.mjs so Go can embed the same values in releases.
type Config struct {
	SchemaVersion   int                          `json:"schemaVersion"`
	BrandID         string                       `json:"brandId"`
	Product         ProductConfig                `json:"product"`
	About           AboutConfig                  `json:"about"`
	Links           map[string]string            `json:"links"`
	Visual          VisualConfig                 `json:"visual"`
	Compatibility   CompatibilityConfig          `json:"compatibility"`
	FutureMigration map[string]string            `json:"futureMigration"`
	Copy            map[string]map[string]string `json:"copy"`
	Platform        PlatformConfig               `json:"platform"`
}

type ProductConfig struct {
	Names       map[string]string `json:"names"`
	ShortName   map[string]string `json:"shortName"`
	Category    map[string]string `json:"category"`
	Tagline     map[string]string `json:"tagline"`
	Description map[string]string `json:"description"`
}

type PlatformConfig struct {
	Windows WindowsBrandConfig `json:"windows"`
}

type WindowsBrandConfig struct {
	FileDescription  map[string]string `json:"fileDescription"`
	InternalName     string            `json:"internalName"`
	OriginalFilename string            `json:"originalFilename"`
}

type AboutConfig struct {
	TeamName      map[string]string `json:"teamName"`
	Copyright     map[string]string `json:"copyright"`
	ContactEmail  string            `json:"contactEmail"`
	SupportEmail  string            `json:"supportEmail"`
	SecurityEmail string            `json:"securityEmail"`
	License       string            `json:"license"`
	Notice        map[string]string `json:"notice"`
}

type VisualConfig struct {
	Logo   map[string]any    `json:"logo"`
	Colors map[string]string `json:"colors"`
}

type CompatibilityConfig struct {
	CLICommand        string `json:"cliCommand"`
	ConfigDir         string `json:"configDir"`
	EnvironmentPrefix string `json:"environmentPrefix"`
	UIProtocol        string `json:"uiProtocol"`
	PairingProtocol   string `json:"pairingProtocol"`
	GoModule          string `json:"goModule"`
}

//go:embed brand.json
var embeddedBrand []byte

var (
	loadOnce sync.Once
	config   Config
)

// Load returns the embedded brand configuration. It is safe for concurrent use
// and never reads from a runtime path, keeping packaged binaries self-contained.
func Load() Config {
	loadOnce.Do(func() {
		if err := json.Unmarshal(embeddedBrand, &config); err != nil {
			panic("invalid embedded brand configuration: " + err.Error())
		}
	})
	return config
}

// Name resolves a locale to the configured product name, first by exact match,
// then by language prefix, then by the configured English default.
func (c Config) Name(locale string) string {
	return localized(c.Product.Names, locale)
}

// Description resolves the localized product description.
func (c Config) Description(locale string) string {
	return localized(c.Product.Description, locale)
}

// WindowsFileDescription resolves the localized Windows file description.
func (c Config) WindowsFileDescription(locale string) string {
	return localized(c.Platform.Windows.FileDescription, locale)
}

// TeamName resolves the configured publisher/team name for a locale.
func (c Config) TeamName(locale string) string {
	return localized(c.About.TeamName, locale)
}

// Copyright resolves the configured copyright notice for a locale.
func (c Config) Copyright(locale string) string {
	return localized(c.About.Copyright, locale)
}

// Text resolves one localized copy entry using the same fallback rules.
func (c Config) Text(key, locale string) string {
	return localized(c.Copy[key], locale)
}

func localized(values map[string]string, locale string) string {
	if values == nil {
		return ""
	}
	if value := values[locale]; value != "" {
		return value
	}
	language := locale
	if idx := strings.IndexByte(language, '-'); idx >= 0 {
		language = language[:idx]
	}
	for key, value := range values {
		if strings.HasPrefix(key, language+"-") && value != "" {
			return value
		}
	}
	if value := values["en-US"]; value != "" {
		return value
	}
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}
